In [1]:
!python -m pip install git+https://github.com/pydata/pandas-datareader.git

Collecting git+https://github.com/pydata/pandas-datareader.git
  Cloning https://github.com/pydata/pandas-datareader.git to c:\users\user\appdata\local\temp\pip-req-build-hrq8v8yk
  Resolved https://github.com/pydata/pandas-datareader.git to commit fdade48126cf588d10c1b207668cf11b314b1861

  Running command git clone --filter=blob:none -q https://github.com/pydata/pandas-datareader.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-hrq8v8yk'

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: lxml in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas-datareader==0.11.0.dev0+6.gfdade48) (4.6.2)
Requirement already satisfied: pandas>=0.23 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas-datareader==0.11.0.dev0+6.gfdade48) (1.3.4)
Requirement already satisfied: requests>=2.19.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas-datareader==0.11.0.dev0+6.gfdade48) (2.25.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.23->pandas-datareader==0.11.0.dev0+6.gfdade48) (2020.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.23->pandas-datareader==0.11.0.dev0+6.gfdade48) (2.8.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.23->pandas-datareader==0.11.0.dev0+6.gfdade48) (1.19.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.19.0->pandas-datareader==0.11.0.dev0+6.gfdade48) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.19.0->pandas-datareader==0.11.0.dev0+6.gfdade48) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.19.0->pandas-datareader==0.11.0.dev0+6.gfdade48) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.19.0->pandas-datareader==0.11.0.dev0+6.gfdade48) (2.10)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader==0.11.0.dev0+6.gfdade48) (1.15.0)
Building wheels for collected packages: pandas-datareader
  Building wheel for pandas-datareader (setup.py): started
  Building wheel for pandas-datareader (setup.py): finished with status 'done'
  Created wheel for pandas-datareader: filename=pandas_datareader-0.11.0.dev0+6.gfdade48-py3-none-any.whl size=110707 sha256=6f4c38487589c8086fefcc8471fcfa8f18ab4379f60715cdf5ef3b66b1800c9e
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-a3l_n8yk\wheels\18\ff\8f\54606005483e63edde2e940e848ee710ddb8adbb2163ae7c63
Successfully built pandas-datareader
Installing collected packages: pandas-datareader
  Attempting uninstall: pandas-datareader
    Found existing installation: pandas-datareader 0.10.0
    Uninstalling pandas-datareader-0.10.0:
      Successfully uninstalled pandas-datareader-0.10.0
Successfully installed pandas-datareader-0.11.0.dev0+6.gfdade48

In [2]:
import pandas_datareader as pdr

In [3]:
pdr.get_data_fred('GS10')

            GS10
DATE
2016-12-01  2.49
2017-01-01  2.43
2017-02-01  2.42
2017-03-01  2.48
2017-04-01  2.30
2017-05-01  2.30
2017-06-01  2.19
2017-07-01  2.32
2017-08-01  2.21
2017-09-01  2.20
2017-10-01  2.36
2017-11-01  2.35
2017-12-01  2.40
2018-01-01  2.58
2018-02-01  2.86
2018-03-01  2.84
2018-04-01  2.87
2018-05-01  2.98
2018-06-01  2.91
2018-07-01  2.89
2018-08-01  2.89
2018-09-01  3.00
2018-10-01  3.15
2018-11-01  3.12
2018-12-01  2.83
2019-01-01  2.71
2019-02-01  2.68
2019-03-01  2.57
2019-04-01  2.53
2019-05-01  2.40
2019-06-01  2.07
2019-07-01  2.06
2019-08-01  1.63
2019-09-01  1.70
2019-10-01  1.71
2019-11-01  1.81
2019-12-01  1.86
2020-01-01  1.76
2020-02-01  1.50
2020-03-01  0.87
2020-04-01  0.66
2020-05-01  0.67
2020-06-01  0.73
2020-07-01  0.62
2020-08-01  0.65
2020-09-01  0.68
2020-10-01  0.79
2020-11-01  0.87
2020-12-01  0.93
2021-01-01  1.08
2021-02-01  1.26
2021-03-01  1.61
2021-04-01  1.64
2021-05-01  1.62
2021-06-01  1.52
2021-07-01  1.32
2021-08-01  1.28
2021-09-01  1.37
2021-10-01  1.58

In [4]:
import datetime
start = datetime.datetime(2016, 2, 19)
end = datetime.datetime(2016, 3, 4)

In [5]:
df = pdr.DataReader('005930.KS', 'yahoo')

In [6]:
df

               High      Low     Open    Close      Volume     Adj Close
Date
2016-11-15  31620.0  30780.0  31060.0  30780.0  13665700.0  26421.267578
2016-11-16  31280.0  30800.0  30800.0  31160.0  13308200.0  26747.453125
2016-11-17  31520.0  30900.0  31100.0  31360.0   7870550.0  26919.134766
2016-11-18  31760.0  31400.0  31640.0  31720.0   9460750.0  27228.152344
2016-11-21  32120.0  31300.0  31300.0  31860.0   8180200.0  27348.326172
...             ...      ...      ...      ...         ...           ...
2021-11-08  70600.0  69800.0  70400.0  70600.0  11121981.0  70600.000000
2021-11-09  71000.0  70100.0  70300.0  70500.0  11159589.0  70500.000000
2021-11-10  70900.0  70200.0  70300.0  70200.0   9422009.0  70200.000000
2021-11-11  70000.0  69600.0  69900.0  69900.0  11489122.0  69900.000000
2021-11-12  70900.0  69900.0  70200.0  70600.0  10087450.0  70600.000000

[1221 rows x 6 columns]

In [7]:
df_samsung = pdr.DataReader('005930.KS', 'yahoo', start, end)
df_samsung.tail()
df_samsung.head()

             High    Low   Open  Close   Volume     Adj Close
Date
2016-02-19  23900  23480  23740  23800  8842600  20415.093750
2016-02-22  23840  23320  23800  23500  8744950  20157.761719
2016-02-23  23780  23460  23580  23620  7383700  20260.697266
2016-02-24  23580  23220  23560  23440  7024200  20106.296875
2016-02-25  23740  23440  23440  23580  6681750  20226.380859